/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/cv/Banner.vue')['default']
    ComingSoon: typeof import('./src/components/portfolio/projects/ComingSoon.vue')['default']
    CreditCheck: typeof import('./src/components/portfolio/projects/CreditCheck.vue')['default']
    Education: typeof import('./src/components/cv/Education.vue')['default']
    Email: typeof import('./src/components/portfolio/projects/Email.vue')['default']
    Experience: typeof import('./src/components/cv/Experience.vue')['default']
    Foodify: typeof import('./src/components/portfolio/projects/Foodify.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Phishing: typeof import('./src/components/portfolio/projects/Phishing.vue')['default']
    ProjectItem: typeof import('./src/components/portfolio/ProjectItem.vue')['default']
    ProjectList: typeof import('./src/components/portfolio/ProjectList.vue')['default']
    RaRaRugby: typeof import('./src/components/portfolio/projects/RaRaRugby.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/cv/Skills.vue')['default']
    SO36: typeof import('./src/components/portfolio/projects/SO36.vue')['default']
    Timeline: typeof import('./src/components/about/Timeline.vue')['default']
  }
}
